# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'JCECircularCollectionViewExample' do

pod 'CircularCollectionView'

end

target 'JCECircularCollectionViewExampleTests' do

end

target 'JCECircularCollectionViewExampleUITests' do

end

